avoid_obstacle_node:
  ros__parameters:
    SPEED_STOP_LINEAR: 0.0
    SPEED_STOP_ANGULAR: 0.0
    SPEED_FORWARD_LINEAR: 0.3
    SPEED_FORWARD_ANGULAR: 0.0
    SPEED_TURN_LINEAR: 0.0
    SPEED_TURN_ANGULAR: 0.3
    OBSTACLE_DISTANCE_THRESHOLD: 1.0
    MIN_THRESHOLD: 0.4
    NON_DETECTION_THRESHOLD: 0.25
    MIN_LASER_RANGE: 4
    DETECTION_PRECISIO: 0.1
    MIN_ROTATION_RADIUS: 0.5